controllers/MainController.php
<?php

namespace app\controllers;

use app\models\Book;
use app\models\Author;
use yii\data\ActiveDataProvider;
use app\models\Search\BookSearch;
use app\models\Search\AuthorSearch;

class MainController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionCatalog()
    {
    	$searchModel = new BookSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);
        $dataProvider->pagination = ['pageSize' => 15];

        return $this->render('catalog', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionReport()
    {
    	$bookCount = Book::find()->count();
    	$authorCount = Author::find()->count();

    	$searchModel = new AuthorSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);

        return $this->render('report', [
        	'bookCount' => $bookCount,
        	'authorCount' => $authorCount,
        	'dataProvider' => $dataProvider,
            'searchModel' => $searchModel
        ]);
    }

}

views/main/catalog.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Author;
use app\models\Book;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AuthorSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Catalog';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="author-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'name',
            'description',
            'isbn',
            [
                'attribute' => 'author_id',
                'filter' => Author::find()->select(['name', 'id'])->indexBy('id')->column(),
                'value' => 'author.name'
            ],
            'author.year',

        ],
    ]); ?>
</div>

views/main/index.php
<?php
use yii\bootstrap\Nav;
/* @var $this yii\web\View */
?>

<?= Nav::widget([
    'options' => ['class' => 'nav nav-pills nav-stacked'],
    'items' => [
        ['label' => Yii::t('app', 'Catalog'), 'url' => ['/main/catalog']],
        ['label' => Yii::t('app', 'Report'), 'url' => ['/main/report']],
        ]
])
?>

views/main/report.php
<?php
use yii\grid\GridView;
?>
	<h1>Отчет</h1>
	<h3>Загальна кількість книг в базі: <?= $bookCount; ?></h3>
	<h3>Загальна кількість авторів в базі: <?= $authorCount; ?></h3><br>
	<?= GridView::widget([
		'dataProvider' => $dataProvider,
		'filterModel' => $searchModel,
		'columns' => [
			['class' => 'yii\grid\SerialColumn'],

			//'id',
			'name',
			'year',
			[
				'label' => 'Count books',
				'value' => function($model)
					{
						return count($model->books);
					}
			],
		],
	]); ?>